session_name: vue-examples
start_directory: "."
windows:
- window_name: edit-run
  layout: even-horizontal
  focus: true
  shell_command_before:
    - echo initial command
  panes:
    - shell_command: nvim -S Session.vim
      focus: true
    - shell_command: echo "started shell"
- window_name: git
  layout: even-horizontal
  panes:
    - shell_command: echo "started shell"
    - vifm .
